DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS rides;

CREATE TABLE cars (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  color TEXT NOT NULL,
  make TEXT NOT NULL,
  model TEXT NOT NULL
);

CREATE TABLE rides (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  duration INTEGER CHECK (duration > 0),
  car_id BIGINT REFERENCES cars(id)
)
