DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS tweets_tags;

CREATE TABLE tweets (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  text VARCHAR(255)
);

CREATE TABLE tags (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(20)
);

CREATE TABLE tweets_tags (
  tweet_id BIGINT REFERENCES tweets(id),
  tag_id BIGINT REFERENCES tags(id),
  PRIMARY KEY(tweet_id, tag_id)
);
