DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS postgram CASCADE;
DROP TABLE IF EXISTS comment;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  profile_photo_url TEXT NOT NULL
);

CREATE TABLE postgram (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) NOT NULL,
  photo_url TEXT NOT NULL,
  caption TEXT,
  tags TEXT[]
);

CREATE TABLE comment (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  comment_by BIGINT REFERENCES users(id) NOT NULL,
  post BIGINT REFERENCES postgram(id) NOT NULL,
  comment TEXT NOT NULL
);
